"""
Tellinen-Madelung magnetic hysteresis model.

This program calculates B-H hysteresis loops for a prescribed magnetic-field
history H(t). Local reversal-branch shapes are generated by the Tellinen model,
while nested reversal-point memory and wiping-out are handled according to the
Madelung rules described in the accompanying report.

Project structure:
    main.py
        Main simulation script. Generates the H(t) excitation history,
        calculates the corresponding B(H) trajectory, plots the hysteresis
        loop, and saves the result to BHloop.csv.

    BH.py
        Core Tellinen-Madelung hysteresis model. Reads Major_Loop.csv,
        constructs continuous upper/lower/initial curves, evaluates the
        Tellinen integrals, builds the first reversal as a raw Tellinen
        branch, maintains Madelung reversal-point memory for higher-order
        branches, and provides BH_increasing() and BH_decreasing().

    Hscan.py
        Defines the test excitation functions Hscan1() and Hscan2().

    Parameters.py
        Reads and validates Parameters.txt.

    Parameters.txt
        Contains the starting magnetic state, numerical tolerances,
        numerical-integration settings, and Hc used by Hscan2().

    Major_Loop.csv
        Input magnetic curves. This file is prepared separately.
        Expected column pairs:
            H_upper, B_upper, H_lower, B_lower [, H_init, B_init]
        The number of points in different column pairs may be different.

    BHloop.csv
        Output file containing the calculated hysteresis trajectory in two
        columns:
            H_A_per_m, B_T

Dependencies:
    Python 3
    NumPy
    SciPy
    Matplotlib

"""

import numpy as np
import matplotlib.pyplot as plt

from Parameters import parameters as par
from BH import (
    BH_increasing,
    BH_decreasing,
    root_branch_value,
    H_MIN,
    H_MAX,
)
from Hscan import Hscan1, Hscan2


# ============================================================
# STARTING MAGNETIC STATE FROM Parameters.txt
# ============================================================

Hstart = par["Hstart"]
root_branch = par["root_branch"]
H_tol = par["H_tol"]

# B at the starting point is obtained from the selected branch.
Bstart = root_branch_value(Hstart, root_branch)


# ============================================================
# GENERATE H(t)
# ============================================================

t_max = 0.1  # time, s
t = np.linspace(0, t_max, 1000)

# Choose a function Hscan(1,2,...) from Hscan.py.
# Hscan.py is deliberately left unchanged. The selected scan is treated
# as a field excursion relative to its own initial value, then shifted so
# that the actual trajectory starts exactly at Hstart from Parameters.txt.
#
# The value of the function H(t) at time t=0 must be consistent
# with the selected simulation starting point defined in the file Parameters.txt.
Hscan_values = Hscan2(t)
Hvalues = Hstart + (Hscan_values - Hscan_values[0])


# ============================================================
# CHECK H RANGE
# ============================================================

if np.min(Hvalues) < H_MIN - H_tol or np.max(Hvalues) > H_MAX + H_tol:
    print(
        "Error: Hscan leaves the H range available in Major_Loop.csv.\n"
        f"Available range: [{H_MIN:g}, {H_MAX:g}] A/m\n"
        f"Requested range: [{np.min(Hvalues):g}, {np.max(Hvalues):g}] A/m"
    )
    raise SystemExit


# ============================================================
# INITIAL STATE
# ============================================================

Hlast = float(Hstart)
Blast = float(Bstart)

# Only real reversal points are stored.
reversal_stack = []

# Previous direction encodes the history already implied by the
# selected root branch.
#
# Upper major branch is normally traversed with decreasing H.
# Lower major branch is normally traversed with increasing H.
# On Binit, a nonzero starting H implies that the material arrived
# there from the demagnetized origin in the corresponding direction.
if root_branch == "upper_major":
    previous_direction = "dec"
elif root_branch == "lower_major":
    previous_direction = "inc"
else:
    if Hstart > H_tol:
        previous_direction = "inc"
    elif Hstart < -H_tol:
        previous_direction = "dec"
    else:
        previous_direction = None


# ============================================================
# ARRAY FOR B VALUES
# ============================================================

Bvalues = np.zeros(len(Hvalues))
Bvalues[0] = Bstart


# ============================================================
# CALCULATE B(H)
# ============================================================

for i, H in enumerate(Hvalues[1:], start=1):

    # ========================================================
    # H HAS NOT CHANGED
    # ========================================================

    if np.isclose(H, Hlast, rtol=0.0, atol=H_tol):
        # B and all state variables remain unchanged.
        B = Blast

        # Important:
        # previous_direction is NOT changed.

    # ========================================================
    # CURRENT H IS INCREASING
    # ========================================================

    elif H > Hlast:

        # On the first movement from H=0 on Binit there is no reversal.
        if previous_direction is None:
            was_inc = True
        else:
            was_inc = (previous_direction == "inc")

        (
            B,
            root_branch,
            reversal_stack,
        ) = BH_increasing(
            H,
            was_inc,
            Hlast,
            Blast,
            root_branch,
            reversal_stack,
        )

        previous_direction = "inc"

    # ========================================================
    # CURRENT H IS DECREASING
    # ========================================================

    else:

        # On the first movement from H=0 on Binit there is no reversal.
        if previous_direction is None:
            was_dec = True
        else:
            was_dec = (previous_direction == "dec")

        (
            B,
            root_branch,
            reversal_stack,
        ) = BH_decreasing(
            H,
            was_dec,
            Hlast,
            Blast,
            root_branch,
            reversal_stack,
        )

        previous_direction = "dec"

    # ========================================================
    # SAVE CURRENT B VALUE
    # ========================================================

    Bvalues[i] = B

    # ========================================================
    # CURRENT POINT BECOMES THE PREVIOUS POINT
    # ========================================================

    Hlast = float(H)
    Blast = float(B)


# ============================================================
# CREATE B-H ARRAY
# ============================================================

BHloop = np.column_stack((Hvalues, Bvalues))


# ============================================================
# DRAW B(H)
# ============================================================

plt.figure(figsize=(7, 6))

plt.plot(
    BHloop[:, 0],
    BHloop[:, 1],
    linewidth=1.5,
)

plt.xlabel("H (A/m)")
plt.ylabel("B (T)")
plt.title("Tellinen-Madelung B-H Hysteresis Loop")

plt.grid(True)

plt.axhline(0.0, linewidth=0.8)
plt.axvline(0.0, linewidth=0.8)

plt.tight_layout()
plt.show()


# ============================================================
# SAVE B-H LOOP TO CSV FILE
# ============================================================

np.savetxt(
    "BHloop.csv",
    BHloop,
    delimiter=",",
    header="H_A_per_m,B_T",
    comments="",
)
